CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(30) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE projects (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    admin_id    BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE leaderboards (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    name        TEXT NOT NULL,
    UNIQUE (project_id, name)
);

CREATE TABLE snapshot_batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leaderboard_id  UUID NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
    snapshot_at     TIMESTAMPTZ NOT NULL,
    top_n           INT NOT NULL DEFAULT 1000 CHECK (top_n > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (leaderboard_id, snapshot_at)
);

CREATE TABLE snapshot_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id     BIGINT NOT NULL REFERENCES snapshot_batches(id) ON DELETE CASCADE,
    rank            INT NOT NULL CHECK (rank > 0),
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score           BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (snapshot_id, user_id)
);

CREATE INDEX idx_leaderboards_project_id ON leaderboards(project_id);
CREATE INDEX idx_projects_admin_id ON projects(admin_id);
CREATE INDEX idx_snapshot_batches_lookup
    ON snapshot_batches (leaderboard_id, snapshot_at DESC);
CREATE INDEX idx_snapshot_entries_snapshot_rank_user
    ON snapshot_entries (snapshot_id, rank ASC, user_id ASC);
