CREATE TABLE api_keys (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    key_hash            VARCHAR(128) NOT NULL UNIQUE,
    key_prefix          VARCHAR(16) NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    rate_limit_per_sec  INT NOT NULL DEFAULT 100 CHECK (rate_limit_per_sec > 0),
    daily_quota         INT NOT NULL DEFAULT 1000000 CHECK (daily_quota > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at          TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ
);

CREATE INDEX idx_api_keys_project_id ON api_keys(project_id);
CREATE INDEX idx_api_keys_status ON api_keys(status);
