CREATE TABLE usage_stats (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id                  BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    bucket_type                 VARCHAR(8) NOT NULL
                                    CHECK (bucket_type IN ('HOUR', 'DAY')),
    bucket_start                TIMESTAMPTZ NOT NULL,
    request_count               BIGINT NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    allowed_count               BIGINT NOT NULL DEFAULT 0 CHECK (allowed_count >= 0),
    blocked_count               BIGINT NOT NULL DEFAULT 0 CHECK (blocked_count >= 0),
    idempotency_hit_count       BIGINT NOT NULL DEFAULT 0 CHECK (idempotency_hit_count >= 0),
    idempotency_miss_count      BIGINT NOT NULL DEFAULT 0 CHECK (idempotency_miss_count >= 0),
    idempotency_conflict_count  BIGINT NOT NULL DEFAULT 0 CHECK (idempotency_conflict_count >= 0),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (api_key_id, bucket_type, bucket_start)
);

CREATE INDEX idx_usage_stats_bucket_lookup
    ON usage_stats (bucket_type, bucket_start DESC);
CREATE INDEX idx_usage_stats_api_key_bucket
    ON usage_stats (api_key_id, bucket_type, bucket_start DESC);
