-- Kafka audit 컨슈머가 적재하는 원본 이벤트.
-- 추이 집계(리더보드별 5분 버킷)와 이상 탐지의 소스이자, 30일 지난 원본을 일 단위로 아카이빙하는 대상.
-- 멱등: relay는 at-least-once라 같은 이벤트가 두 번 배달될 수 있다. (leaderboard_id, event_id) UNIQUE로
--       중복 INSERT를 DB가 거부한다(컨슈머는 ON CONFLICT DO NOTHING). event_id는 한 리더보드 스트림 안에서만
--       고유하므로 leaderboard_id와 짝으로만 유일하다.
CREATE TABLE audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leaderboard_id  UUID        NOT NULL,
    event_id        VARCHAR(40) NOT NULL,   -- Redis 스트림 엔트리 ID "<ms>-<seq>"
    event_time      TIMESTAMPTZ NOT NULL,   -- event_id의 ms 부분(Redis 서버 시계). 버킷 집계 기준.
    event_type      VARCHAR(16) NOT NULL CHECK (event_type IN ('new', 'conflict')),
    user_id         BIGINT      NOT NULL,
    delta           BIGINT      NOT NULL,   -- conflict일 때는 거부된(들어온) 값
    api_key_id      BIGINT      NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (leaderboard_id, event_id)
);

-- 추이 조회: 특정 리더보드의 기간 스캔을 시간순으로. 5분 버킷 집계가 이 인덱스를 탄다.
CREATE INDEX idx_audit_events_leaderboard_time
    ON audit_events (leaderboard_id, event_time);
